In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/fasgadhsxnzmjj/mmd-dataset/centralVN_dataWeather.csv
/kaggle/input/datasets/fasgadhsxnzmjj/mmd-dataset/northVN_dataThoiTiet.csv
/kaggle/input/datasets/fasgadhsxnzmjj/mmd-dataset/southVN_dataAIR.csv
/kaggle/input/datasets/fasgadhsxnzmjj/mmd-dataset/southVN_dataWeather.csv
/kaggle/input/datasets/fasgadhsxnzmjj/mmd-dataset/centralVN_dataAIR.csv
/kaggle/input/datasets/fasgadhsxnzmjj/mmd-dataset/northVN_dataAIR.csv

In [ ]:
Link tổng hợp các bài báo cáo/ nghiên cứu
https://docs.google.com/document/d/1lcOYA7cZFE2UKoTUKJF1JGvXAAc74UfONtuZk0UlKlU/edit?tab=t.0

In [4]:
import pandas as pd

df_air = pd.read_csv("/kaggle/input/datasets/fasgadhsxnzmjj/mmd-dataset/northVN_dataAIR.csv")
df_weather = pd.read_csv("/kaggle/input/datasets/fasgadhsxnzmjj/mmd-dataset/northVN_dataThoiTiet.csv")

In [12]:
df_air[0:20] 
# 2022 - 08 - 04 - 7:00

,district,city,time,pm10 (μg/m³),pm2_5 (μg/m³),carbon_monoxide (μg/m³),carbon_dioxide (ppm),nitrogen_dioxide (μg/m³),sulphur_dioxide (μg/m³),ozone (μg/m³),aerosol_optical_depth (),dust (μg/m³),uv_index (),uv_index_clear_sky ()
0,Ba Dinh,Ha Noi,2022-08-04T00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Ba Dinh,Ha Noi,2022-08-04T01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ba Dinh,Ha Noi,2022-08-04T02:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Ba Dinh,Ha Noi,2022-08-04T03:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Ba Dinh,Ha Noi,2022-08-04T04:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Ba Dinh,Ha Noi,2022-08-04T05:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Ba Dinh,Ha Noi,2022-08-04T06:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Ba Dinh,Ha Noi,2022-08-04T07:00,58.0,40.3,595.0,NaN,29.7,16.8,24.0,0.43,0.0,0.75,0.80
8,Ba Dinh,Ha Noi,2022-08-04T08:00,43.5,30.0,552.0,NaN,25.0,18.2,49.0,0.52,0.0,2.10,2.35
9,Ba Dinh,Ha Noi,2022-08-04T09:00,47.3,32.7,492.0,NaN,18.4,20.2,84.0,0.59,0.0,3.95,4.55
10,Ba Dinh,Ha Noi,2022-08-04T10:00,50.3,34.9,429.0,NaN,11.2,22.0,128.0,0.68,0.0,4.70,6.75
11,Ba Dinh,Ha Noi,2022-08-04T11:00,55.2,38.3,414.0,NaN,8.6,21.5,154.0,0.75,0.0,5.10,8.25
12,Ba Dinh,Ha Noi,2022-08-04T12:00,59.1,41.1,414.0,NaN,7.2,20.1,178.0,0.78,0.0,5.70,8.70
13,Ba Dinh,Ha Noi,2022-08-04T13:00,62.6,43.5,427.0,NaN,8.4,19.0,194.0,0.79,0.0,5.35,7.75
14,Ba Dinh,Ha Noi,2022-08-04T14:00,67.1,46.6,438.0,NaN,11.5,19.6,188.0,0.79,0.0,4.35,5.80
15,Ba Dinh,Ha Noi,2022-08-04T15:00,64.7,45.1,455.0,NaN,16.5,20.9,171.0,0.91,0.0,1.55,3.40
16,Ba Dinh,Ha Noi,2022-08-04T16:00,63.3,44.0,509.0,NaN,26.9,22.5,144.0,0.91,0.0,0.50,1.55
17,Ba Dinh,Ha Noi,2022-08-04T17:00,68.2,47.5,592.0,NaN,40.3,22.8,124.0,0.65,0.0,0.35,0.55
18,Ba Dinh,Ha Noi,2022-08-04T18:00,73.3,51.0,701.0,NaN,57.0,22.9,102.0,0.68,0.0,0.05,0.05
19,Ba Dinh,Ha Noi,2022-08-04T19:00,89.9,62.6,891.0,NaN,78.9,22.8,83.0,0.94,0.0,0.00,0.00

In [11]:
df_weather[0:20]
# 2016 -01 -01 00:00

,district,city,time,temperature_2m (°C),relative_humidity_2m (%),apparent_temperature (°C),precipitation (mm),rain (mm),cloud_cover (%),cloud_cover_low (%),...,wind_speed_100m (km/h),wind_direction_10m (°),soil_temperature_0_to_7cm (°C),soil_temperature_7_to_28cm (°C),soil_temperature_28_to_100cm (°C),soil_temperature_100_to_255cm (°C),soil_moisture_0_to_7cm (m³/m³),soil_moisture_7_to_28cm (m³/m³),soil_moisture_28_to_100cm (m³/m³),soil_moisture_100_to_255cm (m³/m³)
0,Ba Dinh,Ha Noi,2016-01-01T00:00,15.1,80,15.1,0.0,0.0,99,97,...,5.4,347,15.9,16.9,19.8,24.3,0.373,0.375,0.359,0.386
1,Ba Dinh,Ha Noi,2016-01-01T01:00,14.9,82,15.1,0.0,0.0,99,98,...,5.4,353,15.8,16.9,19.8,24.3,0.372,0.375,0.359,0.386
2,Ba Dinh,Ha Noi,2016-01-01T02:00,15.0,81,15.2,0.0,0.0,99,98,...,6.2,360,15.8,16.9,19.8,24.3,0.372,0.375,0.359,0.386
3,Ba Dinh,Ha Noi,2016-01-01T03:00,15.1,76,14.9,0.0,0.0,98,97,...,7.0,8,15.8,16.9,19.8,24.3,0.372,0.375,0.359,0.386
4,Ba Dinh,Ha Noi,2016-01-01T04:00,14.7,78,14.6,0.0,0.0,95,92,...,7.1,14,15.6,16.8,19.8,24.3,0.372,0.374,0.359,0.386
5,Ba Dinh,Ha Noi,2016-01-01T05:00,14.6,80,14.4,0.0,0.0,100,100,...,7.5,18,15.6,16.8,19.8,24.3,0.372,0.374,0.359,0.386
6,Ba Dinh,Ha Noi,2016-01-01T06:00,14.3,82,14.2,0.0,0.0,100,100,...,7.6,45,15.4,16.8,19.8,24.3,0.372,0.374,0.359,0.386
7,Ba Dinh,Ha Noi,2016-01-01T07:00,14.4,83,14.3,0.0,0.0,100,100,...,7.1,61,15.5,16.7,19.8,24.3,0.371,0.374,0.359,0.386
8,Ba Dinh,Ha Noi,2016-01-01T08:00,15.5,70,15.1,0.0,0.0,98,97,...,5.6,58,16.3,16.8,19.8,24.3,0.371,0.374,0.359,0.386
9,Ba Dinh,Ha Noi,2016-01-01T09:00,16.2,67,15.5,0.0,0.0,98,97,...,5.9,55,16.9,16.8,19.8,24.3,0.371,0.374,0.359,0.386
10,Ba Dinh,Ha Noi,2016-01-01T10:00,17.4,63,16.8,0.0,0.0,97,95,...,5.4,48,18.3,17.0,19.8,24.3,0.370,0.373,0.359,0.386
11,Ba Dinh,Ha Noi,2016-01-01T11:00,18.4,61,18.2,0.0,0.0,95,93,...,4.3,41,19.6,17.2,19.7,24.2,0.369,0.373,0.359,0.386
12,Ba Dinh,Ha Noi,2016-01-01T12:00,19.3,60,19.3,0.0,0.0,94,84,...,3.6,45,20.8,17.5,19.7,24.2,0.367,0.372,0.359,0.386
13,Ba Dinh,Ha Noi,2016-01-01T13:00,20.0,59,20.2,0.0,0.0,97,92,...,3.5,63,21.6,17.8,19.7,24.2,0.366,0.372,0.359,0.386
14,Ba Dinh,Ha Noi,2016-01-01T14:00,19.3,63,19.4,0.0,0.0,97,90,...,4.3,84,21.5,18.1,19.7,24.2,0.365,0.371,0.359,0.386
15,Ba Dinh,Ha Noi,2016-01-01T15:00,19.4,64,19.4,0.0,0.0,97,88,...,5.4,95,20.9,18.3,19.7,24.2,0.364,0.371,0.359,0.386
16,Ba Dinh,Ha Noi,2016-01-01T16:00,19.4,64,19.3,0.0,0.0,97,77,...,6.7,106,20.4,18.5,19.7,24.2,0.363,0.371,0.359,0.386
17,Ba Dinh,Ha Noi,2016-01-01T17:00,19.1,66,19.5,0.0,0.0,96,78,...,5.7,106,19.6,18.6,19.7,24.2,0.363,0.370,0.359,0.386
18,Ba Dinh,Ha Noi,2016-01-01T18:00,18.6,70,19.0,0.0,0.0,98,73,...,7.9,85,18.9,18.7,19.8,24.2,0.363,0.370,0.359,0.386
19,Ba Dinh,Ha Noi,2016-01-01T19:00,18.1,77,18.7,0.0,0.0,97,68,...,9.0,85,18.5,18.7,19.8,24.2,0.363,0.370,0.359,0.386

In [34]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df_air['time'] = pd.to_datetime(df_air['time'])

# Lọc toàn bộ dữ liệu trong ngày 30/10/2025
# day_filter = df1[df1['time'].dt.date == pd.to_datetime("2025-10-30").date()]

# Hoặc lọc từ 6:00 sáng đến 12:00 trưa để thấy biến động quanh mốc 9:00
start_time = "2022-08-04 07:00:00"
end_time = "2022-09-04 07:00:00"
window_filter = df_air[(df_air['time'] >= start_time) & (df_air['time'] <= end_time) & (df_air['district'] == "Hoan Kiem")]

df1 = window_filter[['district',	'city'	,'time',	'pm10 (μg/m³)',	'pm2_5 (μg/m³)']]

In [35]:
df1.head()

        district    city                time  pm10 (μg/m³)  pm2_5 (μg/m³)
30679  Hoan Kiem  Ha Noi 2022-08-04 07:00:00          58.0           40.3
30680  Hoan Kiem  Ha Noi 2022-08-04 08:00:00          43.5           30.0
30681  Hoan Kiem  Ha Noi 2022-08-04 09:00:00          47.3           32.7
30682  Hoan Kiem  Ha Noi 2022-08-04 10:00:00          50.3           34.9
30683  Hoan Kiem  Ha Noi 2022-08-04 11:00:00          55.2           38.3